package commodity.pojo;

import java.util.ArrayList;
import java.util.List;

public class CommodityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public CommodityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andImglinkIsNull() {
            addCriterion("imgLink is null");
            return (Criteria) this;
        }

        public Criteria andImglinkIsNotNull() {
            addCriterion("imgLink is not null");
            return (Criteria) this;
        }

        public Criteria andImglinkEqualTo(String value) {
            addCriterion("imgLink =", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkNotEqualTo(String value) {
            addCriterion("imgLink <>", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkGreaterThan(String value) {
            addCriterion("imgLink >", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkGreaterThanOrEqualTo(String value) {
            addCriterion("imgLink >=", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkLessThan(String value) {
            addCriterion("imgLink <", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkLessThanOrEqualTo(String value) {
            addCriterion("imgLink <=", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkLike(String value) {
            addCriterion("imgLink like", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkNotLike(String value) {
            addCriterion("imgLink not like", value, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkIn(List<String> values) {
            addCriterion("imgLink in", values, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkNotIn(List<String> values) {
            addCriterion("imgLink not in", values, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkBetween(String value1, String value2) {
            addCriterion("imgLink between", value1, value2, "imglink");
            return (Criteria) this;
        }

        public Criteria andImglinkNotBetween(String value1, String value2) {
            addCriterion("imgLink not between", value1, value2, "imglink");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andDesriptionIsNull() {
            addCriterion("desription is null");
            return (Criteria) this;
        }

        public Criteria andDesriptionIsNotNull() {
            addCriterion("desription is not null");
            return (Criteria) this;
        }

        public Criteria andDesriptionEqualTo(String value) {
            addCriterion("desription =", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionNotEqualTo(String value) {
            addCriterion("desription <>", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionGreaterThan(String value) {
            addCriterion("desription >", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionGreaterThanOrEqualTo(String value) {
            addCriterion("desription >=", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionLessThan(String value) {
            addCriterion("desription <", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionLessThanOrEqualTo(String value) {
            addCriterion("desription <=", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionLike(String value) {
            addCriterion("desription like", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionNotLike(String value) {
            addCriterion("desription not like", value, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionIn(List<String> values) {
            addCriterion("desription in", values, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionNotIn(List<String> values) {
            addCriterion("desription not in", values, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionBetween(String value1, String value2) {
            addCriterion("desription between", value1, value2, "desription");
            return (Criteria) this;
        }

        public Criteria andDesriptionNotBetween(String value1, String value2) {
            addCriterion("desription not between", value1, value2, "desription");
            return (Criteria) this;
        }

        public Criteria andInventoryIsNull() {
            addCriterion("inventory is null");
            return (Criteria) this;
        }

        public Criteria andInventoryIsNotNull() {
            addCriterion("inventory is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryEqualTo(Integer value) {
            addCriterion("inventory =", value, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryNotEqualTo(Integer value) {
            addCriterion("inventory <>", value, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryGreaterThan(Integer value) {
            addCriterion("inventory >", value, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory >=", value, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryLessThan(Integer value) {
            addCriterion("inventory <", value, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryLessThanOrEqualTo(Integer value) {
            addCriterion("inventory <=", value, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryIn(List<Integer> values) {
            addCriterion("inventory in", values, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryNotIn(List<Integer> values) {
            addCriterion("inventory not in", values, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryBetween(Integer value1, Integer value2) {
            addCriterion("inventory between", value1, value2, "inventory");
            return (Criteria) this;
        }

        public Criteria andInventoryNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory not between", value1, value2, "inventory");
            return (Criteria) this;
        }

        public Criteria andVendoridIsNull() {
            addCriterion("vendorId is null");
            return (Criteria) this;
        }

        public Criteria andVendoridIsNotNull() {
            addCriterion("vendorId is not null");
            return (Criteria) this;
        }

        public Criteria andVendoridEqualTo(String value) {
            addCriterion("vendorId =", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotEqualTo(String value) {
            addCriterion("vendorId <>", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridGreaterThan(String value) {
            addCriterion("vendorId >", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridGreaterThanOrEqualTo(String value) {
            addCriterion("vendorId >=", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLessThan(String value) {
            addCriterion("vendorId <", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLessThanOrEqualTo(String value) {
            addCriterion("vendorId <=", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLike(String value) {
            addCriterion("vendorId like", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotLike(String value) {
            addCriterion("vendorId not like", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridIn(List<String> values) {
            addCriterion("vendorId in", values, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotIn(List<String> values) {
            addCriterion("vendorId not in", values, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridBetween(String value1, String value2) {
            addCriterion("vendorId between", value1, value2, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotBetween(String value1, String value2) {
            addCriterion("vendorId not between", value1, value2, "vendorid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table us_commodity
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 19 12:12:28 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}