package commodity.pojo;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_commodity.id
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_commodity.name
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_commodity.imgLink
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    private String imglink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_commodity.price
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_commodity.desription
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    private String desription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_commodity.inventory
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    private Integer inventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_commodity.vendorId
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    private String vendorid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_commodity.id
     *
     * @return the value of us_commodity.id
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_commodity.id
     *
     * @param id the value for us_commodity.id
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_commodity.name
     *
     * @return the value of us_commodity.name
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_commodity.name
     *
     * @param name the value for us_commodity.name
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_commodity.imgLink
     *
     * @return the value of us_commodity.imgLink
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public String getImglink() {
        return imglink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_commodity.imgLink
     *
     * @param imglink the value for us_commodity.imgLink
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setImglink(String imglink) {
        this.imglink = imglink == null ? null : imglink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_commodity.price
     *
     * @return the value of us_commodity.price
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_commodity.price
     *
     * @param price the value for us_commodity.price
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_commodity.desription
     *
     * @return the value of us_commodity.desription
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public String getDesription() {
        return desription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_commodity.desription
     *
     * @param desription the value for us_commodity.desription
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setDesription(String desription) {
        this.desription = desription == null ? null : desription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_commodity.inventory
     *
     * @return the value of us_commodity.inventory
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_commodity.inventory
     *
     * @param inventory the value for us_commodity.inventory
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_commodity.vendorId
     *
     * @return the value of us_commodity.vendorId
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public String getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_commodity.vendorId
     *
     * @param vendorid the value for us_commodity.vendorId
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    public void setVendorid(String vendorid) {
        this.vendorid = vendorid == null ? null : vendorid.trim();
    }
}