apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-gateway-service
  labels:
    app: us-gateway-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: us-gateway-service
  template:
    metadata:
      labels:
        app: us-gateway-service
    spec:
      containers:
        - name: us-gateway-service
          image: 75560/gateway:v1
          imagePullPolicy: IfNotPresent
#          envFrom:
#            - configMapRef:
#                name: gateway
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: us-gateway-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30010
  selector:
    app: us-gateway-service
