package commodity.mapper;

import commodity.pojo.Commodity;
import commodity.pojo.CommodityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    long countByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int deleteByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int insertSelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    List<Commodity> selectByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    Commodity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int updateByExample(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int updateByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbg.generated Tue Oct 19 12:12:28 CST 2021
     */
    int updateByPrimaryKey(Commodity record);
}