package commodity.mapper;

import commodity.domain.Commodity;
import commodity.domain.CommodityExample;

import java.util.List;


import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int countByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int deleteByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int insertSelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    List<Commodity> selectByExample(CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    Commodity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int updateByExample(@Param("record") Commodity record, @Param("example") CommodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int updateByPrimaryKeySelective(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_commodity
     *
     * @mbggenerated Tue Oct 19 23:18:53 CST 2021
     */
    int updateByPrimaryKey(Commodity record);
}
