version: "3"
services:

  us-gateway-service:
    build: us-gateway-service
    ports:
      - "8000:8000"
    networks:
      - us-service-net

  us-user-service:
    build: us-user-service
    ports:
      - "8001:8001"
    networks:
      - us-service-net

  us-commodity-service:
    build: us-commodity-service
    ports:
      - "8002:8002"
    networks:
      - us-service-net

  us-wallet-service:
    build: us-wallet-service
    ports:
      - "8003:8003"
    networks:
      - us-service-net

  us-order-service:
    build: us-order-service
    ports:
      - "8004:8004"
    networks:
      - us-service-net

  us-cart-service:
    build: us-cart-service
    ports:
      - "8012:8012"
    networks:
      - us-service-net


#  mysql5.7:
#    image: mysql/mysql-server:5.7
#    container_name: mysql57
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: nacos
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    ports:
#      - 3306:3306
#    volumes:
#      - ./docker/mysql/:/var/lib/mysql/
#      - ./docker/conf/:/etc/mysql/
#  nacos:
#    image: nacos/nacos-server:1.2.1
#    container_name: nacos
#    restart: always
#    depends_on:
#      - mysql5.7
#    environment:
#      PREFER_HOST_MODE: hostname #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
#      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
#      MODE: standalone
#      MYSQL_SERVICE_HOST: mysql5.7
#      MYSQL_SERVICE_DB_NAME: nacos
#      MYSQL_SERVICE_PORT: 3306
#      MYSQL_SERVICE_USER: root
#      MYSQL_SERVICE_PASSWORD: root
#      NACOS_APPLICATION_PORT: 8848
#      JVM_XMS: 512m
#      JVM_MMS: 320m
#    volumes:
#      - ./docker/nacos/standalone-logs/:/home/nacos/logs
#      - ./docker/nacos/plugins/:/home/nacos/plugins
#      - ./docker/nacos/conf/application.yml:/home/nacos/conf/application.yml
#    ports:
#      - "8848:8848"
#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus:latest
#    volumes:
#      - ./docker/nacos/prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    depends_on:
#      - nacos
#    restart: on-failure
#  grafana:
#    container_name: grafana
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    restart: on-failure

networks:
  us-service-net: {}