server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false  # 不把自己注册到eureka
    fetch-registry: false  # 不从eureka中获取信息，表明自己是eureka server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: us-eureka-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 75560zcb
    url: jdbc:mysql://106.15.63.203:3306/ultra_seller?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root



