package wallet.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import wallet.domain.Wallet;
import wallet.domain.WalletExample;

public interface WalletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int countByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int deleteByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int deleteByPrimaryKey(Long walletid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int insert(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int insertSelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    List<Wallet> selectByExample(WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    Wallet selectByPrimaryKey(Long walletid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") Wallet record, @Param("example") WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int updateByExample(@Param("record") Wallet record, @Param("example") WalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int updateByPrimaryKeySelective(Wallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_wallet
     *
     * @mbggenerated Mon Nov 08 19:05:30 CST 2021
     */
    int updateByPrimaryKey(Wallet record);
}
