apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-cart-service
  namespace: ase-ns-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-cart-service
  template:
    metadata:
      labels:
        app: us-cart-service
    spec:
      containers:
        - name: us-cart-service
          image: 75560/ultraseller-cart:k8s-deploy2
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8012
          env:
            - name: NACOS_SERVER
              value: 47.102.97.229:8848
            - name: DB_URL
              value: ultraseller-mysql/ultra_seller
            - name: USERNAME
              value: root
            - name: PASSWORD
              value: root
            - name: JAVA_OPTS
              value: "-Xmx1g"
          resources:
              requests:
                cpu: 0.5
                memory: 256Mi
              limits:
                cpu: 1
                memory: 1Gi
          readinessProbe:
              tcpSocket:
                port: 8012
              initialDelaySeconds: 60
              periodSeconds: 10
          livenessProbe:
              tcpSocket:
                port: 8012
              initialDelaySeconds: 60
              periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: us-cart-service
  namespace: ase-ns-12
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8012
  selector:
    app: ultraseller-cart-label