apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-commodity-service
  namespace: ase-ns-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-commodity-service
  template:
    metadata:
      labels:
        app: us-commodity-service
    spec:
      containers:
        - name: us-commodity-service
          image: 75560/ultraseller-commodity:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: us-commodity-service
  namespace: ase-ns-12
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8002
  selector:
    app: us-commodity-service