server:
  port: 8010

mybatis:
  mapper-locations: classpath:mabatis/mapper/*.xml
  type-aliases-package: order.entities.dbo

logging:
  level:
    order: debug

spring:
  application:
    name: us-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.97.229:3306/ultra_seller?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
