mybatis:
  mapper-locations: classpath:mabatis/mapper/*.xml
  type-aliases-package: order.entities.dbo

logging:
  level:
    order: debug

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.97.229:3306/ultra_seller?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  kafka:
    bootstrap-servers: 114.115.145.15:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      properties:
        session:
          timeout:
            ms: 120000
        request:
          timeout:
            ms: 180000
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      missing-topics-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: '*'



