server:
  port: 8010

mybatis:
  mapper-locations: classpath:mabatis/mapper/*.xml
  type-aliases-package: order.entities.dbo

spring:
  application:
    name: ms-cloud-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.97.229:3306/ultra_seller?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
