mybatis:
  mapper-locations: classpath:mabatis/mapper/*.xml
  type-aliases-package: order.entities.dbo

logging:
  level:
    order: debug

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.97.229:3306/ultra_seller?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'
