# Generated by Django 3.2.7 on 2021-11-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('commodity_id', models.CharField(max_length=20)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shopcar',
            },
        ),
    ]
