# Generated by Django 3.2.7 on 2021-11-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='num',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
