apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-commodity-service
  namespace: ase-ns-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-commodity-service
  template:
    metadata:
      labels:
        app: us-commodity-service
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: us-commodity-service
          image: shelahkuang/commodity:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8002
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g"
          resources:
            requests:
              cpu: 0.5
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-order-service
  namespace: ase-ns-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-order-service
  template:
    metadata:
      labels:
        app: us-order-service
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: us-order-service
          image: shelahkuang/order:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8004
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g"
          resources:
            requests:
              cpu: 0.5
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 8004
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8004
            initialDelaySeconds: 60
            periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-user-service
  namespace: ase-ns-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-user-service
  template:
    metadata:
      labels:
        app: us-user-service
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: us-user-service
          image: shelahkuang/user:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8001
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g"
          resources:
            requests:
              cpu: 0.5
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-wallet-service
  namespace: ase-ns-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-wallet-service
  template:
    metadata:
      labels:
        app: us-wallet-service
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: us-wallet-service
          image: shelahkuang/wallet:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8003
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g"
          resources:
            requests:
              cpu: 0.5
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8003
            initialDelaySeconds: 60
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: us-commodity-service
  namespace: ase-ns-12
spec:
  ports:
    - name: http
      port: 8002
  selector:
    app: us-commodity-service

---

apiVersion: v1
kind: Service
metadata:
  name: us-order-service
  namespace: ase-ns-12
spec:
  ports:
    - name: http
      port: 8004
  selector:
    app: us-order-service

---

apiVersion: v1
kind: Service
metadata:
  name: us-user-service
  namespace: ase-ns-12
spec:
  ports:
    - name: http
      port: 8001
  selector:
    app: us-user-service

---

apiVersion: v1
kind: Service
metadata:
  name: us-wallet-service
  namespace: ase-ns-12
spec:
  ports:
    - name: http
      port: 8003
  selector:
    app: us-wallet-service
