apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-commodity-service
  namespace: ase-ns-12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-commodity-service
  template:
    metadata:
      labels:
        app: us-commodity-service
    spec:
      initContainers:
        - image: shelahkuang/skywalking-agent-sidecar:8.6.0
          name: sw-agent-sidecar
          imagePullPolicy: IfNotPresent
          command: [ "sh" ]
          args:
            [
                "-c",
                "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent",
            ]
          volumeMounts:
            - mountPath: /skywalking/agent
              name: sw-agent
      containers:
        - name: us-commodity-service
          image: shelahkuang/commodity:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8002
          env:
            - name: JAVA_OPTS
              value: -javaagent:/usr/skywalking/agent/skywalking-agent.jar
            - name: SW_AGENT_NAME
              value: us-commodity-service
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              # FQDN: servicename.namespacename.svc.cluster.local
              value: oap.ase-ns-12:11800
            - name: SERVER_PORT
              value: "8002"
            - name: SPRING_PROFILES_ACTIVE
              value: test
            - name: SW_AGENT_NAMESPACE
              value: ase-ns-12
          volumeMounts:
            - mountPath: /usr/skywalking/agent
              name: sw-agent
          resources:
            requests:
              cpu: 0.5
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: sw-agent
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: us-commodity-service
  namespace: ase-ns-12
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8002
  selector:
    app: us-commodity-service