apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: ase-ns-12
  labels:
      app: ui-service
spec:
  selector:
    matchLabels:
      app: ui-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service
          image: shelahkuang/ui-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: ase-ns-12
  labels:
      app: ui-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      nodePort: 32677
  selector:
    app: ui-service

---

# apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: ui-service
#  namespace: ase-ns-12
#spec:
#  rules:
#    - host: ui.ultraseller.com
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: ui-service
#              servicePort: 80