apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-mysql-commodity
  namespace: ase-ns-12
spec:
  selector:
    matchLabels:
      app: us-mysql-commodity
  replicas: 1
  template:
    metadata:
      labels:
        app: us-mysql-commodity
    spec:
      containers:
        - name: us-mysql-commodity
          image: shelahkuang/mysql-commodity:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
---

apiVersion: v1
kind: Service
metadata:
  name: us-mysql-commodity
  namespace: ase-ns-12
spec:
  ports:
    - port: 3306
  selector:
    app: us-mysql-commodity