apiVersion: v1
kind: ConfigMap
metadata:
  name: us-global-config
data:
  SW_AGENT_COLLECTOR_BACKEND_SERVICES: "10.176.122.2:11800"
  SW_GRPC_LOG_SERVER_HOST: "10.176.122.2"
  SW_GRPC_LOG_SERVER_PORT: "11800"
  USER_SERVICE_HOST: "us-user-service"
  USER_SERVICE_PORT: "8680"
  GOODS_SERVICE_HOST: "us-commodity-service"
  GOODS_SERVICE_PORT: "8681"
  ORDER_SERVICE_HOST: "us-order-service"
  ORDER_SERVICE_PORT: "8580"
  CART_SERVICE_HOST: "us-cart-service"
  CART_SERVICE_PORT: "8684"
  WALLET_SERVICE_HOST: "us-wallet-service"
  WALLET_SERVICE_PORT: "8685"
  NOTIFICATION_SERVICE_HOST: "us-notification-service"
  NOTIFICATION_SERVICE_PORT: "8590"
  LOGISTICS_SERVICE_HOST: "us-logistics-service"
  LOGISTICS_SERVICE_PORT: "8530"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-rabbitmq-config
data:
  #rabbitmq.host: "47.100.60.194"
  rabbitmq.host: "rabbitmq"
  rabbitmq.username: "admin"
  rabbitmq.password: "admin"
  rabbitmq.port: "5672"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-wallet-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.78:32565/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-user-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.78:32561/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
  server.port: "8680"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-order-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.78:32564/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
  rabbitmq.host: "47.100.60.194"
  rabbitmq.username: "admin"
  rabbitmq.password: "admin"
  rabbitmq.port: "5672"
  server.port: "8580"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-notification-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.78:32566/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
  rabbitmq.host: "47.100.60.194"
  rabbitmq.username: "admin"
  rabbitmq.password: "admin"
  rabbitmq.port: "5672"
  server.port: "8590"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-logistics-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.78:32567/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
  server.port: "8530"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-commodity-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.77:32562/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
  server.port: "8681"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-cart-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.78:32563/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
  server.port: "8684"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: us-gateway-config
data:
  mysql.password: "Six_6g123"
  mysql.url: "jdbc:mysql://10.176.122.78:32561/us-6g?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  mysql.driver-class-name: "com.mysql.cj.jdbc.Driver"
  mysql.username: "six"
  server.port: "8080"
