server:
  port: 8003
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true #是否将自己注册到注册中心
    fetch-registry: true #是否从注册中心服务注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: us-commodity-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 75560zcb
    url: jdbc:mysql://106.15.63.203:3306/ultra_seller?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: commodity.domain
