spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_URL}?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: ${USERNAME}
    password: ${PASSWORD}

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: commodity.domain

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

logging:
  level:
    commodity: debug
