spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 75560zcb
    url: jdbc:mysql://106.15.63.203:3306/ultra_seller?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: commodity.domain

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
