version: "3.4"
services:
  us-cart-service:
    restart: always
    build:
      context: .
      network: host
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python NacosClient.py"
    volumes:
      - .:/code
    ports:
      - "8012:8012"
  #   depends_on:
  #     - db
  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - "./mysql:/var/lib/mysql"
  #   ports:
  #     - "3306:3306"
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mypassword
  #     - MYSQL_DATABASE=django_app