apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-cart-service
  labels:
    app: us-cart-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: us-cart-service
  template:
    metadata:
      labels:
        app: us-cart-service
    spec:
      containers:
        - name: us-cart-service
          image: 75560/cart:v1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-ce", "tail -f /dev/null"]
#          env:
#            - name: NODE_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.hostIP
#          envFrom:
#            - configMapRef:
#                name: walmart-global-config
#            - configMapRef:
#                name: walmart-cart-config
          ports:
            - containerPort: 8012
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: us-cart-service
spec:
  ports:
    - port: 8012
      targetPort: 8012
  selector:
    app: us-cart-service