spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #负载均衡
      routes:
        - id: order-service-route
          uri: lb://us-order-service
          predicates:
            - Path=/order/**
