apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: ase-ns-12
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: apache/skywalking-ui:6.6.0
          ports:
            - containerPort: 8080
              name: page
          env:
            - name: SW_OAP_ADDRESS
              value: oap.ase-ns-12:12800
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: ase-ns-12
  labels:
    service: ui
spec:
  ports:
    - port: 8080
      name: page
      nodePort: 31234
  type: LoadBalancer
  selector:
    app: ui